### ISSUE TITLE
Add non-interactive mode for scripted execution

### ISSUE THREAD

**Issue by WoLpH** [NicoHood/gpgit#11]
Right now the script always asks for confirmation making it impossible to execute `gpgit` from other release scripts: https://github.com/NicoHood/gpgit/blob/4ee493d453c04ff5bbce130fa5102622f23fcf9f/gpgit.py#L953

It would be useful to have a `yes` parameter

Note that this can be worked around through: `yes | gpgit ...`

**Comment by NicoHood** [comment]
Closing as I switched back to bash. I dont know if I will use the python version again, bash seems still simpler to code and easier to install.
