### ISSUE TITLE
Release message not escaped correct sometimes

### ISSUE THREAD

**Issue by NicoHood** [NicoHood/gpgit#29]
As [reported](https://github.com/NicoHood/gpgit/pull/19#issuecomment-772379943) by @WoLpH it looks like some release messages are not escaped correctly.

**Comment by NicoHood** [comment]
@WoLpH is this still an issue for you? I am struggling on reproducing this issue.

**Comment by WoLpH** [comment]
I believe it's been fixed already. I haven't seen any issues since :)
