### ISSUE TITLE
Should `user.githubtoken` be replaced with `gpgit.token`?

### ISSUE THREAD

**Issue by WoLpH** [NicoHood/gpgit#9]
Right now the code is asking for `user.githubtoken`: https://github.com/NicoHood/gpgit/blob/4ee493d453c04ff5bbce130fa5102622f23fcf9f/gpgit.py#L658

But it appears to be reading from `gpgit.token`: https://github.com/NicoHood/gpgit/blob/4ee493d453c04ff5bbce130fa5102622f23fcf9f/gpgit.py#L784-L800

**Comment by NicoHood** [comment]
Closing as I switched back to bash. I dont know if I will use the python version again, bash seems still simpler to code and easier to install.
